import type { Metadata } from "next";
import "./globals.css";

import Providers from "@/app/providers";

import { Toaster } from "@/components/ui/sonner";

import { mtnBrighterSans } from "@/app/fonts";

export const metadata: Metadata = {
  title: "Intern Compass",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${mtnBrighterSans.variable} antialiased`}>
      <body className="font-sans">
        <Providers>{children}</Providers>

        <Toaster />
      </body>
    </html>
  );
}
