export const departments = [
  "Chief Executive Officer Office",
  "Chief Operating Officer Office",
  "Company Secretariat",
  "Corporate Services and Sustainability",
  "Customer Relations and Experience",
  "Digital Services",
  "Enterprise Business",
  "Finance",
  "Fixed BroadBand",
  "Human Resources",
  "Information Technology",
  "Internal Audit and Forensic Services",
  "Marketing",
  "Network",
  "Risk and Compliance",
  "Sales and Distribution",
  "Strategy and Innovation",
];

export const programmingLanguages = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C#",
  "C / C++",
  "Go",
  "Rust",
  "PHP",
  "Ruby",
  "Swift",
  "Kotlin",
  "Dart",
  "Scala",
  "SQL / PL/SQL",
  "Bash / Shell scripting",
];

export const technicalPathways = [
  "Frontend Web Development",
  "Backend / API Development",
  "Fullstack Development",
  "Mobile App Development",
  "Cloud Computing / DevOps",
  "Data Science / Machine Learning",
  "Cybersecurity / Ethical Hacking",
  "Embedded Systems / IoT",
  "Game Development",
  "Blockchain / Web3",
  "Software Testing / QA",
  "AI / NLP / Computer Vision",
  "Database Administration / Big Data",
];

export const softSkills = [
  "Communication",
  "Presentation Skills",
  "Active Listening",
  "Negotiation",
  "Leadership",
  "Team Management",
  "Project Management",
  "Strategic Planning",
  "Decision Making",
  "Problem Solving",
  "Critical Thinking",
  "Conflict Resolution",
  "Time Management",
  "Organization",
  "Adaptability / Flexibility",
  "Collaboration / Teamwork",
  "Empathy / Emotional Intelligence",
  "Customer Focus",
  "Business Acumen",
  "Innovation / Creativity",
  "Stakeholder Management",
  "Change Management",
  "Other",
];
